---
# https://dependabot.com/docs/config-file/

version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
      - match:
          update_type: "all"
          dependency_type: "direct"
      - match:
          update_type: "security"
          dependency_type: "indirect"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
    commit_message:
      prefix: "build"
      include_scope: true
         
